from __future__ import annotations

import os
from pathlib import Path
import subprocess
import sys
import tempfile
import textwrap
import unittest


ROOT = Path(__file__).resolve().parents[1]
ACTION = ROOT / ".github" / "actions" / "no-ai-attribution" / "action.yml"


class AttributionActionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.repository = Path(self.temporary.name)
        self.environment = {
            key: os.environ[key]
            for key in ("PATH", "SYSTEMROOT", "TEMP", "TMP")
            if key in os.environ
        }
        self.environment.update(
            GIT_CONFIG_NOSYSTEM="1",
            GIT_CONFIG_GLOBAL=os.devnull,
            GIT_AUTHOR_NAME="Example Maintainer",
            GIT_AUTHOR_EMAIL="maintainer@example.invalid",
            GIT_COMMITTER_NAME="Example Maintainer",
            GIT_COMMITTER_EMAIL="maintainer@example.invalid",
            PYTHONIOENCODING="utf-8",
        )
        self.git("init", "--quiet", "-b", "main")
        self.base = self.commit("Initial source")
        self.head = self.commit("Update source")

    def git(self, *arguments: str) -> str:
        return subprocess.run(
            ["git", *arguments],
            cwd=self.repository,
            env=self.environment,
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=True,
        ).stdout.strip()

    def commit(self, message: str) -> str:
        self.git("commit", "--quiet", "--allow-empty", "-m", message)
        return self.git("rev-parse", "HEAD")

    def run_policy(self, **values: str) -> subprocess.CompletedProcess[str]:
        self.assertTrue(ACTION.is_file(), "the shared attribution action is missing")
        action = ACTION.read_text(encoding="utf-8")
        self.assertEqual(action.count("python - <<'PY'\n"), 1)
        script = textwrap.dedent(action.split("python - <<'PY'\n", 1)[1])
        self.assertTrue(script.rstrip().endswith("\nPY"))
        script = script.rstrip().removesuffix("\nPY")
        environment = (
            self.environment
            | {
                "BASE_SHA": self.base,
                "HEAD_SHA": self.head,
                "PR_TITLE": "Handle responses generated by OpenAI API",
                "PR_BODY": "Technical product references are allowed.",
            }
            | values
        )
        return subprocess.run(
            [sys.executable, "-c", script],
            cwd=self.repository,
            env=environment,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )

    def test_clean_commits_and_technical_product_references_pass(self) -> None:
        result = self.run_policy()
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("No AI attribution found.", result.stdout)

    def test_title_and_body_credits_fail(self) -> None:
        for values in (
            {"PR_TITLE": "Generated by Claude Code"},
            {"PR_BODY": "Summary\n\nGenerated with ChatGPT"},
            {"PR_BODY": "Co-authored-by: Codex <example@example.invalid>"},
        ):
            with self.subTest(values=values):
                result = self.run_policy(**values)
                self.assertEqual(result.returncode, 1)
                self.assertIn("AI attribution found:", result.stdout)

    def test_fenced_example_is_allowed_but_following_credit_fails(self) -> None:
        example = "~~~text\nGenerated by Claude Code\n~~~\n"
        self.assertEqual(self.run_policy(PR_BODY=example).returncode, 0)
        result = self.run_policy(PR_BODY=example + "Generated with ChatGPT")
        self.assertEqual(result.returncode, 1)
        self.assertIn("pull request body line 4", result.stdout)

    def test_commit_trailers_fail_including_on_initial_push(self) -> None:
        self.head = self.commit("Update\n\nCo-authored-by: Codex <example@example.invalid>")
        for base in (self.base, "0" * 40):
            with self.subTest(base=base):
                result = self.run_policy(BASE_SHA=base)
                self.assertEqual(result.returncode, 1)
                self.assertIn("co-author trailer", result.stdout)

    def test_raw_author_and_committer_cannot_be_hidden_by_mailmap(self) -> None:
        (self.repository / ".mailmap").write_text(
            "Example Maintainer <maintainer@example.invalid> <noreply@anthropic.com>\n",
            encoding="utf-8",
        )
        self.git("add", ".mailmap")
        for role in ("AUTHOR", "COMMITTER"):
            with self.subTest(role=role):
                self.environment[f"GIT_{role}_EMAIL"] = "noreply@anthropic.com"
                self.head = self.commit("Update source")
                result = self.run_policy()
                self.assertEqual(result.returncode, 1)
                self.assertIn(f"AI {role.lower()} identity", result.stdout)
                self.environment[f"GIT_{role}_EMAIL"] = "maintainer@example.invalid"
                self.base = self.head

    def test_invalid_and_unavailable_commit_ranges_fail_closed(self) -> None:
        for head, message in (
            ("--all", "Invalid commit identifier"),
            ("f" * 40, "commit fetch failed"),
        ):
            with self.subTest(head=head):
                result = self.run_policy(HEAD_SHA=head)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(message, result.stdout + result.stderr)

    def test_pull_request_text_is_data_and_cannot_execute_a_command(self) -> None:
        result = self.run_policy(
            PR_TITLE="Handle $(touch executed) in a quoted example",
            PR_BODY="`touch executed`\n$(touch executed)",
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertFalse((self.repository / "executed").exists())


if __name__ == "__main__":
    unittest.main()
