#!/usr/bin/env bash
# Exercise .githooks/commit-msg, the local copy of the attribution rules that
# refuses a credit at the keyboard rather than after a push.
#
# The hook and the shared action must agree, and where they differ the hook is
# deliberately the stricter of the two. Every case below is either a parity case
# lifted from tests/test_attribution_action.py or a regression that a previous
# revision of the hook let through.
set -u

HOOK=${1:-$(cd "$(dirname "$0")/.." && pwd)/.githooks/commit-msg}
WORK=$(mktemp -d)
trap 'cd /; rm -rf "$WORK"' EXIT
cd "$WORK" || exit 1
git init -q .

pass=0
fail=0

# run <allow|block> <label> <message> [author-name] [author-email]
#     [committer-name] [committer-email]
run() {
	want=$1
	label=$2
	msg=$3
	an=${4:-Ryan Duguid}
	ae=${5:-ryan@duguid.com.au}
	cn=${6:-$an}
	ce=${7:-$ae}
	printf '%s\n' "$msg" >msg.txt
	if GIT_AUTHOR_NAME="$an" GIT_AUTHOR_EMAIL="$ae" \
		GIT_COMMITTER_NAME="$cn" GIT_COMMITTER_EMAIL="$ce" \
		"$HOOK" msg.txt >/dev/null 2>err.txt; then
		verdict=allow
	else
		verdict=block
	fi
	if [ "$verdict" = "$want" ]; then
		pass=$((pass + 1))
		printf 'ok   %-6s %s\n' "$want" "$label"
	else
		fail=$((fail + 1))
		printf 'FAIL want=%-6s got=%-6s %s\n' "$want" "$verdict" "$label"
		sed 's/^/         /' err.txt | head -3
	fi
}

echo "--- credits that must be refused ---"
run block "co-author trailer" 'Fix

Co-Authored-By: Claude <noreply@anthropic.com>'
run block "session trailer" 'Fix

Claude-Session: https://claude.ai/code/session_01'
run block "robot emoji footer" 'Fix

🤖 Generated with [Claude Code](https://claude.com/claude-code)'
run block "generated-with footer" 'Fix

Generated with Claude Code'
run block "credit verb: reviewed by" 'Fix

Reviewed by Claude'
run block "bare vendor url" 'Fix

https://claude.ai/code/session_123'
run block "bot co-author account" 'Fix

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>'
run block "credit behind a comment marker" 'Fix
# Co-Authored-By: Claude <noreply@anthropic.com>'
run block "credit split across a folded trailer" 'Fix

Co-authored-by: Contributor
    Claude <noreply@anthropic.com>'
run block "vendor name split by a zero-width character" "$(printf 'Fix\n\nGenerated with Cla\xe2\x80\x8bude Code')"
run block "four-space fence is not a fence" 'Document the policy

    ```
Generated with Claude Code'

echo "--- regressions a previous revision let through ---"
run block "credit starting a folded continuation" 'Fix

Notes: some context
    Generated by Claude'
run block "indented closing fence still closes its block" 'Document the policy

```
Notes: quoted
   ```
Generated with Claude Code'
run block "repeated comment markers are peeled in turn" 'Fix
## Co-Authored-By: Claude <noreply@anthropic.com>'
# The backticks below are literal message text, not a command substitution.
# shellcheck disable=SC2016
run block "backtick opener with a backtick info string opens nothing" 'Document the policy

``` `not a fence
Generated with Claude Code'
run block "non-printable character in the author name" 'Publish' "$(printf 'Ryan\tDuguid')"
run block "non-printable character in the committer name" 'Publish' \
	'Ryan Duguid' 'ryan@duguid.com.au' "$(printf 'Ryan\tDuguid')" 'ryan@duguid.com.au'

echo "--- messages that must be allowed ---"
run allow "product reference in a subject" 'feat: publish the skills as a Claude Code plugin'
run allow "human co-author" 'Fix

Co-authored-by: Ryan Duguid <ryan@duguid.com.au>'
run allow "dependabot co-author" 'chore: bump ruff

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>'
run allow "quoted example inside a fence" 'Document the policy

```
Co-Authored-By: Claude <noreply@anthropic.com>
```

That is the rule.'
run allow "longer fence survives a shorter marker" 'Document the policy

````
```
Co-Authored-By: Claude <noreply@anthropic.com>
```
````

That is the rule.'
run allow "editor template commentary" 'Fix a thing
# Please enter the commit message for your changes.
# On branch claude/remove-git-coauthorship-m9hvep
# Changes to be committed:
#	modified:   file.md'
run allow "indented prose under a trailer key" 'Fix

Notes: some context
    on a continuation line.'

echo "--- identities (parity with the shared action) ---"
run block "author at a blocked address" 'Publish' 'Claude' 'noreply@anthropic.com'
run block "committer at a blocked address" 'Publish' \
	'Ryan Duguid' 'ryan@duguid.com.au' 'Claude' 'noreply@anthropic.com'
run block "bot account in a noreply address" 'Publish' \
	'claude[bot]' '1+claude[bot]@users.noreply.github.com'
run block "model-qualified name" 'Publish' 'Claude Opus' 'someone@example.com'
run block "agent role name" 'Publish' 'Review Bot' 'bot@example.com'
run allow "a person" 'Publish' 'Ryan Duguid' 'ryan@duguid.com.au'
run allow "a person whose name contains a vendor word" 'Publish' \
	'Claude Fontaine' 'claude.fontaine@example.com'
run allow "a person at a vendor domain" 'Publish' 'Alice Smith' 'alice@anthropic.com'
run allow "dependabot identity" 'chore: bump ruff' \
	'dependabot[bot]' '49699333+dependabot[bot]@users.noreply.github.com'

echo "--- comment marker configuration ---"
git config core.commentChar ';'
run block "the configured marker is peeled" 'Fix
; Co-Authored-By: Claude <noreply@anthropic.com>'
run allow "another character is ordinary text" 'Fix
# Generated with Claude Code'
git config --unset core.commentChar

git config core.commentChar auto
run block "auto resolves to any marker git may pick" 'Fix
; Co-Authored-By: Claude <noreply@anthropic.com>'
git config --unset core.commentChar

if git config core.commentString '//' 2>/dev/null; then
	run block "core.commentString is read too" 'Fix
// Co-Authored-By: Claude <noreply@anthropic.com>'
	git config --unset core.commentString
else
	echo "skip      core.commentString unsupported by this git"
fi

echo
echo "commit-msg hook: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
