name: PR review trigger

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: 'true'
